### ISSUE TITLE
Add ES6 in the code 

### ISSUE THREAD

**Issue by SatyamSB** [WandXDapp/WandXOptionsDapp#2]
We need to use the import export functionality of the ES6

**Comment by bssrdev** [comment]
@SatyamSB we are already using import and export functionality. If I am wrong anywhere, please elaborate.

**Comment by bssrdev** [comment]
In front end or Backend.

**Comment by SatyamSB** [comment]
in backend, we are not using babel

**Comment by bssrdev** [comment]
No Satyam, we are not using babel. Should we use ?

**Comment by satyamakgec** [comment]
Yes, otherwise we are not able to use the ES6 in our backend

**Comment by bssrdev** [comment]
Cool, I am installing the package now.
I will be running this command and adding this package.
`npm install --save-dev babel-cli babel-preset-env`

**Comment by bssrdev** [comment]
Done
